cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

lukas/urls.py
from django.contrib import admin
from django.urls import path, include

from main import IndexView, ErrorView, WishlistView, AboutView, GalleryView, ContactsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', IndexView.as_view()),
    path('index/', IndexView.as_view()),
    path('404/', ErrorView.as_view()),
    path('wishlist/', WishlistView.as_view()),
    path('gallery/', GalleryView.as_view()),
    path('about/', AboutView.as_view()),
    path('contact/', ContactsView.as_view()),
    path('', include("shop.urls", namespace='shop')),
    path('orders/', include('order.urls', namespace='order')),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.product_list, name='product_list'),
    path('single/<int:id>/<slug:slug>/', views.product_details,
         name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models

from shop.models import Product


# Create your models here.


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    ordering = ('name',)
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=20, unique=True, verbose_name='Сокр. название')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bike:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=100, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=100,db_index=True, unique=True, verbose_name='Сокр. название')
    image = models.ImageField(upload_to="static/img/db/", blank=True, verbose_name='Изображение')
    description = models.TextField(max_length=100, blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    available = models.BooleanField(default=True, verbose_name='В продаже')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bike:product_details', args=[self.id, self.slug])


class AdditionalProductImage(models.Model):
    image = models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Изображение')
    product = models.ForeignKey(Product, related_name='additional_images', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(max_value=99, min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

order/forms.py
from django import forms

from order.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Product


# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart.html', {'cart': cart})

order/views.py
from django.shortcuts import render

from cart.cart import Cart
from order.forms import OrderCreateForm
from order.models import OrderItem


# Create your views here.
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request, 'thankyou.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'checkout.html', {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart import cart
from cart.cart import Cart
from cart.forms import CartAddProductForm
from shop.models import Category, Product


# Create your views here.
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {cart}
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop.html', {'category': category, 'categories': categories, 'products': products})


def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'single-product.html', {'product': product, 'cart_product_form': cart_product_form})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Home 2 :: Lukas - Car Parts Store eCommerce HTML Template</title>

    <!--== Favicon ==-->
    <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon" />

    <!--== Google Fonts ==-->
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,500,600,700%7CPoppins:400,400i,500,600&display=swap" rel="stylesheet">

    <!-- build:css ../static/css/app.min.css -->
    <!--== Leaflet Min CSS ==-->
    <link href="/static/css/leaflet.min.css" rel="stylesheet" />
    <!--== Nice Select Min CSS ==-->
    <link href="/static/css/nice-select.min.css" rel="stylesheet" />
    <!--== Slick Slider Min CSS ==-->
    <link href="/static/css/slick.min.css" rel="stylesheet" />
    <!--== Magnific Popup Min CSS ==-->
    <link href="/static/css/magnific-popup.min.css" rel="stylesheet" />
    <!--== Slicknav Min CSS ==-->
    <link href="/static/css/slicknav.min.css" rel="stylesheet" />
    <!--== Animate Min CSS ==-->
    <link href="/static/css/animate.min.css" rel="stylesheet" />
    <!--== Ionicons Min CSS ==-->
    <link href="/static/css/ionicons.min.css" rel="stylesheet" />
    <!--== Font-Awesome Min CSS ==-->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet" />
    <!--== Bootstrap Min CSS ==-->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" />

    <!--== Main Style CSS ==-->
    <link href="/static/css/style.css" rel="stylesheet" />
    <!--== Helper Min CSS ==-->
    <link href="/static/css/helper.min.css" rel="stylesheet" />
    <!-- endbuild -->

    <!--[if lt IE 9]>
<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>

    <!--== Start Header Area ==-->
    <header class="header-area">
        <div class="container container-wide">
            <div class="row align-items-center">
                <div class="col-sm-4 col-lg-2">
                    <div class="site-logo text-center text-sm-left">
                        <a href="/index/"><img src="/static/img/logo.png" alt="Logo" /></a>
                    </div>
                </div>

                <div class="col-lg-7 d-none d-lg-block">
                    <div class="site-navigation">
                        <ul class="main-menu nav">
                            <li class="has-submenu"><a href="/index/">Home</a>
                            </li>
                            <li><a href="/about/">About</a></li>
                            <li class="has-submenu"><a href="/shop/">Shop</a>
                            </li>
                            <li class="has-submenu"><a href="/404/">blog</a>
                                <ul class="sub-menu">
                                    <li><a href="/404/">Blog Left Sidebar</a></li>
                                    <li><a href="/404/">Blog Right Sidebar</a></li>
                                    <li><a href="/404/">Single Blog</a></li>
                                    <li><a href="/404/">Single Blog Sidebar</a></li>
                                </ul>
                            </li>
                            <li><a href="/gallery/">Gallery</a></li>
                            <li class="has-submenu"><a href="/index/">Pages</a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
                                    <li><a href="{% url "order:order_create" %}">Checkout</a></li>
                                    <li><a href="/wishlist/">Wishlist</a></li>
                                </ul>
                            </li>
                            <li><a href="/contact/">Contact</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-sm-8 col-lg-3">
                    <div class="site-action d-flex justify-content-center justify-content-sm-end align-items-center">
                        <ul class="login-reg-nav nav">
                            <li><a href="#">Login</a></li>
                            <li><a href="#">Register</a></li>
                        </ul>

                        <div class="mini-cart-wrap">

                            <a href="{% url 'cart:cart_detail' %}" class="btn-mini-cart">
                                <i class="ion-bag"></i>
                               <span class="cart-total">{{ cart|length }}</span>

                            </a>

                            <div class="mini-cart-content">
                                <div class="mini-cart-product">
                                    {% for item in cart %}
                                    {% with product=item.product %}
                                    <div class="mini-product">
                                        <div class="mini-product__thumb">
                                            <a href="/single/{{ product.id }}/{{ product.slug }}"><img src="{{product.image.url}}" alt="product" /></a>
                                        </div>
                                        <div class="mini-product__info">
                                            <h2 class="title"><a href="/single/{{ product.id }}/{{ product.slug }}">{{ product.name}}</a></h2>

                                            <div class="mini-calculation">
                                                <p class="price">{{ item.quantity }} x <span>${{ product.price }}</span></p>
                                                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                    <button class="remove-pro"><i class="ion-trash-b"></i></button>
                                                     {% csrf_token %}
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    {% endwith %}
                                {% endfor %}


                                </div>
                            </div>
                        </div>

                        <div class="responsive-menu d-lg-none">
                            <button class="btn-menu">
                                <i class="fa fa-bars"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--== End Header Area ==-->

    {% block content %}
    {% endblock %}

    <!--== Start Footer Area Wrapper ==-->
    <footer class="footer-area">
        <div class="footer-widget-area">
            <div class="container container-wide">
                <div class="row mtn-40">
                    <div class="col-lg-3">
                        <div class="widget-item">
                            <div class="about-widget">
                                <a href="/index/"><img src="/static/img/logo-light.png" alt="Logo" /></a>
                                <p>Lukas is the best parts shop for your car
                                    accessories. What kind of parts do you
                                    need you can get here soluta nobis</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-2">
                        <div class="widget-item">
                            <h4 class="widget-title">Information</h4>
                            <div class="widget-body">
                                <ul class="widget-list">
                                    <li><a href="#">Our company</a></li>
                                    <li><a href="#">Contact us</a></li>
                                    <li><a href="#">Our services</a></li>
                                    <li><a href="#">Why We?</a></li>
                                    <li><a href="#">Careers</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-2">
                        <div class="widget-item">
                            <h4 class="widget-title">Quicklink</h4>
                            <div class="widget-body">
                                <ul class="widget-list">
                                    <li><a href="#">About</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Shop</a></li>
                                    <li><a href="#">Cart</a></li>
                                    <li><a href="#">Contact</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-2">
                        <div class="widget-item">
                            <h4 class="widget-title">Support</h4>
                            <div class="widget-body">
                                <ul class="widget-list">
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Contact</a></li>
                                    <li><a href="#">Return Policy</a></li>
                                    <li><a href="#">Online Support</a></li>
                                    <li><a href="#">Money Back</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-lg-3">
                        <div class="widget-item">
                            <h4 class="widget-title">Store Information</h4>
                            <div class="widget-body">
                                <address>
                                    2005 Stokes Isle Apartment. 896, Washington 10010, USA <br>
                                https://example.com <br>
                                (+68) 120034509
                            </address>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-copyright-area">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <div class="copyright-content">
                            <p>Copyright © 2019 Lukas. All Rights Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--== End Footer Area Wrapper ==-->

    <!-- Scroll Top Button -->
    <button class="btn-scroll-top"><i class="ion-chevron-up"></i></button>



    <!--== Start Responsive Menu Wrapper ==-->
    <aside class="off-canvas-wrapper off-canvas-menu">
        <div class="off-canvas-overlay"></div>
        <div class="off-canvas-inner">
            <!-- Start Off Canvas Content -->
            <div class="off-canvas-content">
                <div class="off-canvas-header">
                    <div class="logo">
                        <a href="/index/"><img src="/static/img/logo.png" alt="Logo"></a>
                    </div>
                    <div class="close-btn">
                        <button class="btn-close"><i class="ion-android-close"></i></button>
                    </div>
                </div>

                <!-- Content Auto Generate Form Main Menu Here -->
                <div class="res-mobile-menu mobile-menu">

                </div>
            </div>
        </div>
    </aside>
    <!--== End Responsive Menu Wrapper ==-->


    <!--=======================Javascript============================-->
    <!-- build:js ../static/js/app.min.js -->
    <!--=== Modernizr Min Js ===-->
    <script src="/static/js/modernizr-3.6.0.min.js"></script>
    <!--=== jQuery Min Js ===-->
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <!--=== jQuery Migration Min Js ===-->
    <script src="/static/js/jquery-migrate-1.2.1.min.js"></script>
    <!--=== Popper Min Js ===-->
    <script src="/static/js/popper.min.js"></script>
    <!--=== Bootstrap Min Js ===-->
    <script src="/static/js/bootstrap.min.js"></script>
    <!--=== Slicknav Min Js ===-->
    <script src="/static/js/jquery.slicknav.min.js"></script>
    <!--=== Magnific Popup Min Js ===-->
    <script src="/static/js/jquery.magnific-popup.min.js"></script>
    <!--=== Slick Slider Min Js ===-->
    <script src="/static/js/slick.min.js"></script>
    <!--=== Nice Select Min Js ===-->
    <script src="/static/js/jquery.nice-select.min.js"></script>
    <!--=== Leaflet Min Js ===-->
    <script src="/static/js/leaflet.min.js"></script>
    <!--=== Countdown Js ===-->
    <script src="/static/js/countdown.js"></script>

    <!--=== Active Js ===-->
    <script src="/static/js/active.js"></script>
    <!-- endbuild -->

</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% block content %}

    <div class="page-header-wrap bg-img" data-bg="/static/img/bg/page-header-bg.jpg">
        <div class="container">
            <div class="row">
                <div class="col-12 text-center">
                    <div class="page-header-content">
                        <div class="page-header-content-inner">
                            <h1>Shopping Cart</h1>
                            <ul class="breadcrumb">
                                <li><a href="/index/">Home</a></li>
                                <li><a href="/shop/">Shop</a></li>
                                <li class="current"><a href="#">Cart</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<!--== Start Page Content Wrapper ==-->
<div class="page-content-wrapper sp-y">
    <div class="cart-page-content-wrap">
        <div class="container container-wide">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping-cart-list-area">
                        <div class="shopping-cart-table table-responsive">
                            <table class="table table-bordered text-center mb-0">
                                <thead>
                                <tr>
                                    <th>Products</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for item in cart %}
                                    {% with product=item.product %}
                                <tr>
                                    <td class="product-list">
                                        <div class="cart-product-item d-flex align-items-center">
                                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                            <div class="remove-icon">
                                                <button><i class="fa fa-trash-o"></i></button>
                                            </div>
                                             {% csrf_token %}
                                            </form>
                                            <a href="/single/{{ product.id }}/{{ product.slug }}" class="product-thumb">
                                                <img src="{{ product.image.url }}" alt="Product" />
                                            </a>
                                            <a href="/single/{{ product.id }}/{{ product.slug }}" class="product-name">{{ product.name}}</a>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="price">${{ item.price }}</span>
                                    </td>
                                    <td>
                                        <div class="pro-qty">
                                            <input type="text" class="quantity" title="Quantity" value="{{ item.quantity }}" />
                                        </div>
                                    </td>
                                    <td>
                                        <span class="price">${{ item.total_price }}</span>
                                    </td>
                                </tr>
                                {% endwith %}
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>

                        <div class="cart-coupon-update-area d-sm-flex justify-content-between align-items-center">
                            <div class="coupon-form-wrap">
                                <form action="#" method="post">
                                    <label for="coupon" class="sr-only">Coupon Code</label>
                                    <input type="text" id="coupon" placeholder="Coupon Code" />
                                    <button class="btn-apply">Apply Button</button>
                                </form>
                            </div>

                            <div class="cart-update-buttons mt-15 mt-sm-0">
                                <button class="btn-clear-cart">Clear Cart</button>
                                <button class="btn-update-cart">Update Cart</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <!-- Cart Calculate Area -->
                    <div class="cart-calculate-area mt-sm-40 mt-md-60">
                        <h5 class="cal-title">Cart Totals</h5>

                        <div class="cart-cal-table table-responsive">
                            <table class="table table-borderless">
                                <tr class="cart-sub-total">
                                    <th>Subtotal</th>
                                    <td>${{ cart.get_total_price }}</td>
                                </tr>
                                <tr class="shipping">
                                    <th>Shipping</th>
                                    <td>
                                        <ul class="shipping-method">
                                            <li>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" id="flat_shipping" name="shipping_method" class="custom-control-input"  />
                                                    <label class="custom-control-label" for="flat_shipping">Flat Rate :
                                                        $10</label>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" id="free_shipping" name="shipping_method" class="custom-control-input" checked/>
                                                    <label class="custom-control-label" for="free_shipping">Free
                                                        Shipping</label>
                                                </div>
                                            </li>
                                            <li>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" id="cod_shipping" name="shipping_method" class="custom-control-input" />
                                                    <label class="custom-control-label" for="cod_shipping">Cash on
                                                        Delivery</label>
                                                </div>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                                <tr class="order-total">
                                    <th>Total</th>
                                    <td><b>${{ cart.get_total_price }}</b></td>
                                </tr>
                            </table>
                        </div>

                        <div class="proceed-checkout-btn">
                            <a class="btn btn-brand d-block"href=" {% url "order:order_create" %}">Proceed to Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--== End Page Content Wrapper ==-->

{% endblock %}

templates/thankyou.html
{% extends 'base.html' %}
{% load static %}
{% block title %}SHOP{% endblock %}
{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3">Thank you!</h2>
            <p class="lead mb-5">You order was successfuly completed. Your order number is <strong>{{ order.id }}</strong>.</p>
          </div>
        </div>
      </div>
    </div>

{% endblock %}